config/routes.rb
Rails.application.routes.draw do

  root "price_plans#index"

  resources :price_plans do
    resources :supply_nodes
    resources :telemetry_nodes
    resources :telemetry_channels
    resources :charges
  end

end

app/models/charge.rb
class Charge

  include Mongoid::Document
  include Mongoid::Timestamps


  field :type, type: Symbol
  field :price_setter, type: Symbol

  embeds_many :periods

  def self.charge_type
    [:network_daily, :flick_daily, :metering, :ea_levy, :flick_kwh, :network_kwh]
  end

  def self.price_setter_type
    [:flick, :network, :electricity_auth, :meter_company]
  end

end

app/models/period.rb
class Period

  include Mongoid::Document
  include Mongoid::Timestamps

  field :type, type: Symbol
  field :applicable_start_time, type: Time
  field :applicable_end_time, type: Time

  embeds_many :segments

  def self.period_type
    [:winter, :summer, :all_year]
  end

  def rate_amt=(amt)
    if /^[\d]+(\.[\d]+){0,1}$/ === amt.gsub(/\$/, "")
      money_amt = Monetize.parse(amt, "NZD")
      if [Fixnum, Money].include? money_amt.class
        self.rate = money_amt.cents if money_amt.is_a? Money
      else
        errors.add(:amt, "Amount is not a Money value")
      end
    else
      errors.add(:amt, "Amount does not appear to be a number") unless /^[\d]+(\.[\d]+){0,1}$/ === amt.gsub(/\$/, "")
    end
  end

  def rate_amt(options = {})
    raise ArgumentError, 'The "options" arg must be a Hash' unless options.is_a? Hash
    options[:in] ||= 'NZD'
    self.rate.nil? ? cents = 0 : cents = self.rate
    f = Money.new(cents, options[:in])
  end


end

app/models/price_plan.rb
class PricePlan

  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :category, type: String
  field :network, type: String
  field :description, type: String
  field :type, type: String
  field :industry_id, type: String

  embeds_many :supply_nodes

  embeds_many :telemetry_nodes

  embeds_many :telemetry_channels


  def self.category_options
    [:uncontrolled, :controlled, :controlled_uncontrolled]
  end

  def self.industry_id_options
    [:g100, :g200 ]
  end

  def self.type_options
    [:low_user, :standard]
  end

  def self.network_options
    [:wellington]
  end

  def create_it(params)
    self.name = params[:name]
    self.category = params[:category].to_sym
    self.network = params[:network].to_sym
    self.description = params[:description]
    self.type = params[:type].to_sym
    self.industry_id = params[:industry_id].to_sym
    self.save
    self
  end

  def success_create_event
    :successful_plan_create_event
  end


end

app/models/segment.rb
class Segment

  include Mongoid::Document
  include Mongoid::Timestamps


  field :rate_unit, type: Symbol
  field :rate, type: Integer
  field :rate_per, type: Symbol

  field :duration, type: String
  field :start_time, type: Time

  def rate_amt=(amt)
    if /^[\d]+(\.[\d]+){0,1}$/ === amt.gsub(/\$/, "")
      money_amt = Monetize.parse(amt, "NZD")
      if [Fixnum, Money].include? money_amt.class
        self.rate = money_amt.cents if money_amt.is_a? Money
      else
        errors.add(:amt, "Amount is not a Money value")
      end
    else
      errors.add(:amt, "Amount does not appear to be a number") unless /^[\d]+(\.[\d]+){0,1}$/ === amt.gsub(/\$/, "")
    end
  end

  def rate_amt(options = {})
    raise ArgumentError, 'The "options" arg must be a Hash' unless options.is_a? Hash
    options[:in] ||= 'NZD'
    self.rate.nil? ? cents = 0 : cents = self.rate
    f = Money.new(cents, options[:in])
  end


end

app/models/supply_node.rb
class SupplyNode

  include Mongoid::Document
  include Mongoid::Timestamps

  field :registered_price_category, type: Symbol

  embeds_many :charges

  def create_it(params)
    self.registered_price_category = params[:registered_price_category].to_sym
    self.save
    self
  end

  def successful_create_event
    :successful_supply_node_create_event
  end

  def type_of
    self.class.name
  end

end

app/models/telemetry_channel.rb
class TelemetryChannel

  include Mongoid::Document
  include Mongoid::Timestamps

  field :channel_code, type: String

  embeds_many :charges

end

app/models/telemetry_node.rb
class TelemetryNode

  include Mongoid::Document
  include Mongoid::Timestamps

  field :registered_price_category, type: Symbol

  embeds_many :charges

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @plan = PricePlanQueryHandler.new(PricePlan).find(params[:price_plan_id])
    @charge = PricePlanService.new(Charge).empty_charge
    @node = params[:node]
    @node_type = params[:node_type]
  end

  def create
    @charge = PricePlanService.new(Charge).empty_charge(plan: @plan, for: params[:node], type: params[:node_type])
  end

  def successful_supply_node_create_event(plan)
    @plan = plan
  end

end

app/controllers/price_plans_controller.rb
class PricePlansController < ApplicationController

  def index
    @plans = PricePlanQueryHandler.new(PricePlan).get_all
  end

  def new
    @plan = PricePlanService.new(PricePlan).empty_plan
  end

  def create
    plan = PricePlanService.new(PricePlan.new)
    plan.subscribe(self)
    plan.create_plan(params[:price_plan])
  end

  def show
    @plan = PricePlanQueryHandler.new(PricePlan).find(params[:id])
  end


  # Events

  def successful_plan_create_event(plan)
    redirect_to price_plans_path
  end


end

app/controllers/supply_nodes_controller.rb
class SupplyNodesController < ApplicationController

  def new
    @plan = PricePlanQueryHandler.new(PricePlan).find(params[:price_plan_id])
    @supply = PricePlanService.new(SupplyNode).empty_node
  end

  def create
    plan = PricePlanQueryHandler.new(PricePlan).find(params[:price_plan_id])
    supply = PricePlanService.new(SupplyNode.new)
    supply.subscribe(self)
    supply.create_node_plan(plan, params[:supply_node])
  end

  def successful_supply_node_create_event(plan)
    @plan = plan
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def category_options
    PricePlan.category_options.collect {|c| [c.to_s, c]}
  end

  def plan_selects(option)
    PricePlan.send(option).collect {|c| [c.to_s, c]}
  end

  def charges_select(option)
    Charge.send(option).collect {|c| [c.to_s, c]}
  end

  def periods_select(option)
    Period.send(option).collect {|c| [c.to_s, c]}
  end


end

app/views/charges/_form.html.erb
<%= form_for([@plan, @charge], node: @node, node_type: @node_type,  html: { class: "custom"}) do |f| %>

  <div class="row">
    <div class="small-2 columns">
      <%= f.label :type, class: "right inline", title: "Type of Charge", data: {tooltip: true } %>
    </div>
    <div class="small-10 columns">
        <%= f.select(:type, options_for_select(charges_select(:charge_type)), :include_blank => true, :prompt => "Select a option") %>
    </div>

  </div>

  <div class="row">
    <div class="small-2 columns">
      <%= f.label :price_setter, class: "right inline", title: "WHo Set the Price", data: {tooltip: true } %>
    </div>
    <div class="small-10 columns">
        <%= f.select(:price_setter, options_for_select(charges_select(:price_setter_type)), :include_blank => true, :prompt => "Select a option") %>
    </div>

  </div>

  <%= render partial: "periods" %>


<% end %>

app/views/charges/_periods.html.erb
<div class="row">
  <div class="small-6 columns">
    <div class="small-6 columns">
      <%= label_tag(:period_type, nil, class: "right inline", title: "name the period", data: {tooltip: true }) %>
    </div>
    <div class="small-6 columns">
      <%= select_tag(:period_type, options_for_select(periods_select(:period_type)), :include_blank => true, :prompt => "Select a option") %>
    </div>

  </div>
  <div class="small-6 columns">

  </div>
</div>

app/views/charges/new.html.erb
<%= render partial: "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
    <%= render partial: 'shared/top_nav'  %> 

    <%= yield %>

  </body>
</html>

app/views/price_plans/_form.html.erb
<%= form_for(@plan, html: { class: "custom"}) do |f| %>

   <div class="row">
     <div class="small-2 columns">
       <%= f.label :name, class: "right inline", title: "Formal Name for the Plan", data: {tooltip: true } %>
     </div>
     <div class="small-10 columns">
       <%= f.text_field :name, placeholder: "Formal name" %>
     </div> 
     
   </div>


   <div class="row">
     <div class="small-2 columns">
       <%= f.label :category, class: "right inline", title: "Plan Category", data: {tooltip: true } %>
     </div>
     <div class="small-10 columns">
         <%= f.select(:category, options_for_select(category_options), :include_blank => true, :prompt => "Select a option") %>

     </div> 
   </div>

   <div class="row">
     <div class="small-2 columns">
       <%= f.label :network, class: "right inline", title: "Config the Category", data: {tooltip: true } %>
     </div>
     <div class="small-10 columns">
         <%= f.select(:network, options_for_select(plan_selects(:network_options)), :include_blank => true, :prompt => "Select a network") %>

     </div> 
   </div>

   <div class="row">
     <div class="small-2 columns">
       <%= f.label :description, class: "right inline", title: "A catchy description of the plan", data: {tooltip: true } %>
     </div>
     <div class="small-10 columns">
       <%= f.text_field :description, placeholder: "A catchy description of the plan" %>
     </div> 
   </div>
   
   <div class="row">
     <div class="small-2 columns">
       <%= f.label :type, class: "right inline", title: "the type", data: {tooltip: true } %>
     </div>
     <div class="small-10 columns">
         <%= f.select(:type, options_for_select(plan_selects(:type_options)), :include_blank => true, :prompt => "Select a type") %>

     </div> 
   </div>
  

   <div class="row">
     <div class="small-2 columns">
       <%= f.label :industry_id, class: "right inline", title: "Map the industry Id", data: {tooltip: true } %>
     </div>
     <div class="small-10 columns">
         <%= f.select(:industry_id, options_for_select(plan_selects(:industry_id_options)), :include_blank => true, :prompt => "Map the industry Id") %>

     </div> 
   </div>



   <div class="row">
     <div class="small-10 small-offset-2 columns">
       <%= f.submit 'Submit', :class => 'button small' %>
     </div>
   </div>
   
   
<% end %>

app/views/price_plans/_price_plan.html.erb
<div class="row">
   <div class="small-1 columns">
      <i class="fi-dollar %> size-30"></i>
   </div>
   <div class="small-11 columns">
      <h5><%= link_to plan.name, price_plan_path(plan) %></h5>
   </div>
 </div>
 <div class="row">
   <%= link_to "New Supply Node Charges", new_price_plan_supply_node_path(plan), class: "button small" %>
</div>
<div class="row">
</div>

app/views/price_plans/_price_plans.html.erb
<% @plans.each do |plan|%>
  <div class="panel">
    <%= render partial: "price_plan", locals: {plan: plan} %>
 </div>

<% end %>

app/views/price_plans/index.html.erb
<div class="row">
   <div class="large-2 columns">
      "icon_bar"
      <%= link_to "New Plan", new_price_plan_path, class: :button%>
   </div>
   <div class="large-10 columns">
      <div class="row">
         <div id="search"></div>
      </div>
      <div class="row">
         <div class="large-7 columns">
            <div id = "plans">
               <%= render 'price_plans'%>
            </div>
         </div>
         <div class="large-5 columns">
            <div id='plan'></div>
         </div>

      </div>
   </div>
</div>

app/views/price_plans/new.html.erb
<%= render partial: "form"%>

app/views/price_plans/show.html.erb
<div class="row">
   <div class="small-1 columns">
      Name
   </div>
   <div class="small-5 columns">
     <%= @plan.name %>
   </div>
   <div class="small-1 columns">
      Category
   </div>
   <div class="small-5 columns">
     <%= @plan.category %>
   </div>
</div>

<div class="row">
   <div class="small-1 columns">
      Network
   </div>
   <div class="small-5 columns">
     <%= @plan.network %>
   </div>
   <div class="small-1 columns">
      Description
   </div>
   <div class="small-5 columns">
     <%= @plan.description %>
   </div>
</div>

<div class="row">
   <div class="small-1 columns">
      Type
   </div>
   <div class="small-5 columns">
     <%= @plan.type %>
   </div>
   <div class="small-1 columns">
      Industry Id
   </div>
   <div class="small-5 columns">
     <%= @plan.industry_id %>
   </div>
</div>

<%= link_to "Plans", rates_price_plans_path, class: "button" %>

app/views/rates/price_plans/index.html.erb
<div class="row">
   <div class="large-2 columns">
      "icon_bar"
      <%= link_to "New Plan", new_rates_price_plan_path, class: :button%>
   </div>
   <div class="large-10 columns">
      <div class="row">
         <div id="search"></div>
      </div>
      <div class="row">
         <div class="large-7 columns">
            <div id = "plans">
               <%= render 'price_plans'%>
            </div>
         </div>
         <div class="large-5 columns">
            <div id='plan'></div>
         </div>
         
      </div>
   </div>
</div>

app/views/shared/_top_nav.html.erb
 <div class="icon-bar six-up">
   <a class="item">
     <i class="fi-home"></i>
     <label>Home</label>
   </a>

   <%= link_to(price_plans_path, class: "item") do %>
     <i class="fi-pricetag-multiple"></i>
     <label>Plans</label>
   <% end %>

 </div>

app/views/supply_nodes/_form.html.erb
<%= form_for([@plan, @supply], remote: true, html: { class: "custom"}) do |f| %>

   <div class="row">
     <div class="small-2 columns">
       <%= f.label :registered_price_category, class: "right inline", title: "", data: {tooltip: true } %>
     </div>
     <div class="small-10 columns">
       <%= f.text_field :registered_price_category, placeholder: "" %>
     </div>

   </div>

   <div class="row">
     <div class="small-10 small-offset-2 columns">
       <%= f.submit 'Submit', :class => 'button small' %>
     </div>
   </div>


<% end %>

<div id="create-charges">
</div>

<div id="new-change-form">
</div>

app/views/supply_nodes/_new_charge.html.erb
<%= link_to("Add a Supply Node Charge", new_price_plan_charge_path(@plan.plan, node: @plan.node_plan, node_type: @plan.node_plan.type_of), class: "button") %>

app/views/supply_nodes/new.html.erb
<%= render partial: "form"%>